web/src/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from .yasg import urlpatterns as swagger_url
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

admin_url = settings.ADMIN_URL

urlpatterns = [
    path('actions/', include('actions.urls')),
    path('user-profile/', include('user_profile.urls')),
    path('', include('main.urls')),
    path('auth/', include('auth_app.urls')),
    path('', include('blog.urls')),
    path('', include('contact_us.urls')),
    path(f'{admin_url}/', admin.site.urls),
    path(f'{admin_url}/defender/', include('defender.urls')),
    path('api/', include('rest_framework.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('about/', include('about.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += swagger_url

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    if settings.ENABLE_SILK:
        urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]
    if settings.ENABLE_DEBUG_TOOLBAR:
        from debug_toolbar import urls

        urlpatterns += [path('__debug__/', include(urls))]

web/user_profile/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework.routers import DefaultRouter

from . import views

app_name = 'user_profile'

router = DefaultRouter()

router.register('profile', views.ProfileViewSet)
router.register('user', views.UserViewSet)


urlpatterns = [
    path('', views.ProfileViewSet.as_view({'get': 'profile'}), name='user_profile'),
]

urlpatterns += [
    path('true-users/', views.TrueUserViewSet.as_view({'get': 'user_list'}), name='api_list_true_users'),
    path('password-change/', views.UserViewSet.as_view({"post": 'password_change'}), name='password_change'),
    path('update-image/', views.UserViewSet.as_view({"post": 'update_image'}), name='update_image'),
    path('<id>/', views.ProfileViewSet.as_view({'get': 'retrieve'}), name='user_profile_id'),
]

urlpatterns += router.urls

web/user_profile/models.py
from urllib.parse import urljoin

from django.db import models
from django.contrib.auth import get_user_model

from src import settings
from . import managers
from . import choices

User = get_user_model()


# Create your models here.
class Profile(models.Model):
    objects = models.Manager()
    gender = models.IntegerField(choices=choices.GenderChoice.choices, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    image = models.ImageField(
        upload_to="profile/", default="default_avatar.jpg")  # height_field=100, width_field=100)
    birthdate = models.DateField(null=True, blank=True)
    bio = models.TextField(max_length=2000, help_text="Bio", default='')
    website = models.URLField(max_length=300, default='', blank=True)

    def avatar_url(self):
        return urljoin(settings.BACKEND_SITE, self.image.url)

    def __str__(self):
        return str(self.user.full_name())

web/user_profile/views.py
import logging
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView
from drf_yasg.utils import swagger_auto_schema
from rest_framework.generics import GenericAPIView
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin
from rest_framework.permissions import AllowAny
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework import status, viewsets
from rest_framework.viewsets import ModelViewSet
from rest_framework.decorators import action
from rest_framework.permissions import BasePermission, IsAdminUser, IsAuthenticatedOrReadOnly
from django.core.cache import cache
from .models import Profile
from . import services
from . import serializers
from django.contrib.auth import get_user_model
from .services import UserProfileService
from dj_rest_auth import views as auth_views
from rest_framework.parsers import MultiPartParser

User = get_user_model()
logger = logging.getLogger(__name__)


class ViewSet(ModelViewSet):
    # http_method_names = ('get', 'put')
    # permission_classes = (AllowAny,)

    def get_permissions(self):
        if self.action == 'retrieve':
            permission_classes = (IsAuthenticatedOrReadOnly,)
        else:
            permission_classes = (AllowAny,)
        return [permission() for permission in permission_classes]


class UserViewSet(viewsets.GenericViewSet):
    # template_name = "user-profile.html"
    queryset = User.objects.all()

    # parser_classes = [MultiPartParser]

    def get_template_name(self):
        if self.action == 'user':
            return 'user-profile.html'
        elif self.action == 'password_change':
            return 'user_profile/reset_password_email_link.html'
        else:
            return 'user-profile.html'

    def get_serializer_class(self):
        if self.action == 'user':
            return serializers.UserProfileSerializer
        if self.action == 'password_change':
            return serializers.ChangePasswordSerializer
        if self.action == "update_image":
            return serializers.ChangeImageSerializer
        return serializers.UserProfileSerializer

    def update_image(self, request):
        serializer = self.get_serializer(data=request.data, instance=request.user.profile)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data)

    def password_change(self, request):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response({"data": "changed successfully"})

    def user(self, request):
        serializer = self.get_serializer(request.user)
        return Response(serializer.data, template_name=self.template_name)


class ProfileViewSet(ViewSet, RetrieveModelMixin, UserViewSet):
    template_name = "user-profile.html"
    serializer_class = serializers.UserProfileSerializer
    lookup_field = "id"

    def profile(self, request):
        serializer = self.get_serializer(request.user)
        return Response(serializer.data, template_name=self.template_name)

    def perform_create(self, serializer):
        serializer.save()

    # def get_queryset(self):
    #     print(self.kwargs)
    #     return UserProfileService.get_user_profile_queryset(user_id=self.kwargs.get("id"))
    def retrieve(self, request, *args, **kwargs):
        instance = self.get_object()
        serializer = self.get_serializer(instance)
        return Response(serializer.data)
        # response = super().list(request, **kwargs)
        # response.template_name = self.template_name
        # return response


class TrueUserViewSet(viewsets.GenericViewSet):
    template_name = "user-list.html"  # страница со списком пользователей
    serializer_class = serializers.TrueUserSerializer

    def get_queryset(self):
        true_users = cache.get('true_users')
        if true_users is None:
            true_users = UserProfileService.get_user_queryset()
            cache.set('true_users', true_users, timeout=120)
        return true_users

    def user_list(self, request):
        serializer = self.get_serializer(self.get_queryset(), many=True)
        return Response({"users": serializer.data}, template_name=self.template_name)

    def perform_create(self, serializer):
        serializer.save()

web/user_profile/templates/user-list.html
{% load static %}

<link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<br><br>
<div class="container">
 <div class="well span8 offset2">
   {% for user in users %}
        <div class="row-fluid user-row">
            <div class="span1">
                <img class="img-circle"
                     src="{{ user.image }}"
                     alt="User Pic">
            </div>
            <div class="span10">
                <strong>{{ user.birthdate }}</strong><br>
                <a href="{% url 'user_profile:user_profile_id'  user.id %}"><strong>{{ user.full_name }}</strong></a><br>
            </div>
            <div class="span1 dropdown-user" data-for=".cyruxx">
                <i class="icon-chevron-down text-muted"></i>
            </div>
        </div>
        <div class="row-fluid user-infos cyruxx">
            <div class="span10 offset1">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <h3 class="panel-title">User information</h3>
                    </div>
                    <div class="panel-body">
                        <div class="row-fluid">
                            <div class="span3">
                                <img class="img-circle"
                                     src="{{ user.image }}"
                                     alt="User Pic">
                            </div>
                            <div class="span6">

                                <table class="table table-condensed table-responsive table-user-information">
                                    <tbody>
                                    <tr>
                                         {% if user.gender == 0 %}
                                            <tr><td class="active">Gender:</td><td> Male </td></tr>
                                         {% endif %}
                                         {% if user.gender == 1 %}
                                            <tr><td class="active">Gender:</td><td> Female </td></tr>
                                         {% endif %}
                                    </tr>
                                    <tr>
                                        <td>Birthday:</td>
                                        <td> {{ user.birthdate }}</td>
                                    </tr>
                                    <tr>
                                        <td>Bio:</td>
                                        <td> {{ user.bio }}</td>
                                    </tr>
                                    <tr>
                                        <td>Website:</td>
                                        <td> {{ user.website }}</td>
                                    </tr>

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="send-message" data-id="{{ user.id }}" data-href="http://localhost:10000/init/">
                        <button class="btn  btn-primary" type="button"
                                data-toggle="tooltip"
                                data-original-title="Send message to user"><i class="icon-envelope icon-white"></i></button>
                        </div>
                        <span class="pull-right">
                            <button class="btn btn-warning" type="button"
                                    data-toggle="tooltip"
                                    data-original-title="Edit this user"><i class="icon-edit icon-white"></i></button>
                            <button class="btn btn-danger" type="button"
                                    data-toggle="tooltip"
                                    data-original-title="Remove this user"><i class="icon-remove icon-white"></i></button>
                        </span>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
</div>
<script>
  $(document).ready(function(){
    $.getScript('{% static 'user_profile/js/user-list.js' %}');
    {% block jquery %} {% endblock jquery %}
})
</script>

web/user_profile/templates/user-profile.html
{% load static %}
{% load i18n main %}
{% microservice_title as site_name %}
{% block content %}
<title>User profile</title>
{% block head %}
<link rel="stylesheet" href="https://bootstraptema.ru/plugins/2015/bootstrap3/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
<script src="https://bootstraptema.ru/plugins/jquery/jquery-1.11.3.min.js"></script>
<script src="https://bootstraptema.ru/plugins/2015/b-v3-3-6/bootstrap.min.js"></script>
{% endblock head %}
<script>
  $(document).ready(function(){
    $.getScript('{% static 'user_profile/js/user-profile.js' %}');
    $.getScript('{% static 'user_profile/js/connect_chat.js' %}');
    {% block jquery %} {% endblock jquery %}
})
</script>
<br><br><br>

<style>
body{background:url(https://bootstraptema.ru/images/bg/bg-1.png)}

#main {
 background-color: #f2f2f2;
 padding: 20px;
-webkit-border-radius: 4px;
 -moz-border-radius: 4px;
 -ms-border-radius: 4px;
 -o-border-radius: 4px;
 border-radius: 4px;
 border-bottom: 4px solid #ddd;
}
#real-estates-detail #author img {
 -webkit-border-radius: 100%;
 -moz-border-radius: 100%;
 -ms-border-radius: 100%;
 -o-border-radius: 100%;
 border-radius: 100%;
 border: 5px solid #ecf0f1;
 margin-bottom: 10px;
}
#real-estates-detail .sosmed-author i.fa {
 width: 30px;
 height: 30px;
 border: 2px solid #bdc3c7;
 color: #bdc3c7;
 padding-top: 6px;
 margin-top: 10px;
}
.panel-default .panel-heading {
 background-color: #fff;
}
#real-estates-detail .slides li img {
 height: 450px;
}
</style>

<div class="container">
<div id="main">


 <div class="row" id="real-estates-detail">
 <div class="col-lg-4 col-md-4 col-xs-12">
 <div class="panel panel-default">
 <div class="panel-heading">
 <header class="panel-title">
 <div class="text-center">
 <strong>Пользователь сайта <input type="text" data-href="{% url 'user_profile:user_profile' %}" name="full_name" id="full_name" value={{ full_name }}> </strong>
 </div>
 </header>
 </div>
 <div class="panel-body">
 <div class="text-center" id="author">
 <img src="{{ image }}" width="240" height="240" id="userAvatar">
<input id="updateImageInput" data-href="{% url 'user_profile:update_image' %}" type="file" name="image" value="Обзор...">
   <a id="chat-connect" data-href="http://localhost:10000/init/" data-id="3" class="btn btn-primary">Написать сообщение</a>
 </div>
 </div>
 </div>
 </div>
 <div class="col-lg-8 col-md-8 col-xs-12">
 <div class="panel">
 <div class="panel-body">
 <ul id="myTab" class="nav nav-pills">
 <li class="active"><a href="#detail" data-toggle="tab">О пользователе</a></li>
 <li class=""><a href="#changepswd" class="btn btn-link pull-right" data-toggle="modal" data-target="#pwdModalChange"> Смена пароля </a></li>
 <li class=""><a href="{% url 'user_profile:api_list_true_users' %}">Посмотреть список пользователей</a></li>
 </ul>
 <div id="myTabContent" class="tab-content">
<hr>
 <div class="tab-pane fade active in" id="detail">
 <h4>История профиля</h4>
 <table class="table table-th-block">
 <tbody>
  <tr><td class="active">Дата рождения:</td><td> <input type="text" data-href="{% url 'user_profile:user_profile' %}" name="birthdate" id="birthdate" value={{ birthdate }}>
</td></tr>
 {% if gender == 0 %}
    <tr><td class="active">Пол:</td><td>  <input type="text" data-href="{% url 'user_profile:user_profile' %}" name="gender" id="gender" value="Male">
 </td></tr>
 {% endif %}
 {% if gender == 1 %}
    <tr><td class="active">Пол:</td><td>  <input type="text" data-href="{% url 'user_profile:user_profile' %}" name="gender" id="gender" value="Female">
 </td></tr>
 {% endif %}
 <tr><td class="active">Веб-сайт:</td><td> <input type="text" data-href="{% url 'user_profile:user_profile' %}" name="website" id="website" value={{ website }}>
</td></tr>
 <tr><td class="active">Биография:</td><td> <input type="text" data-href="{% url 'user_profile:user_profile' %}" name="bio" id="bio" value={{ bio }}>
</td></tr>
</tbody>
 </table>
 </div>
 </div>
 </div>
 </div>
 </div>
 </div>
</div>

</div><!-- /.main -->
</div><!-- /.container -->
{% include 'user_profile/reset_password_email_link.html' %}
{% endblock %}