web/auth_app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.conf import settings
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView
from main.views import TemplateAPIView
from . import views

app_name = 'auth_app'

router = DefaultRouter()

urlpatterns = [
    path('token/refresh/', TokenRefreshView.as_view()),
    path('token/verify/', TokenVerifyView.as_view()),
]

urlpatterns += [
    path('sign-in/', views.LoginView.as_view(), name='api_login'),
    path('sign-up/', views.SignUpView.as_view(), name='api_sign_up'),
    path('sign-up/verify/', views.VerifyEmailView.as_view(), name='api_sign_up_verify'),
    path('password/reset/', views.PasswordResetView.as_view(), name='api_forgot_password'),
    path('password/reset/confirm/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm_email'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

urlpatterns += router.urls

urlpatterns += [
    path('password-reset/<uidb64>/<token>/', TemplateView.as_view(
        template_name='auth_app/includes/reset_password_email_link.html'), name='password_reset_confirm'),
    path('verify-email/<key>/', TemplateAPIView.as_view(template_name='auth_app/success_enter_link.html'),
         name='account_verification'),
]

if settings.ENABLE_RENDERING:
    urlpatterns += [
        path('login/', TemplateAPIView.as_view(template_name='auth_app/login.html'), name='login'),
        path('register/', TemplateAPIView.as_view(template_name='auth_app/sign_up.html'), name='sign_up'),
        path('verify-email/success', TemplateAPIView.as_view(
            template_name='auth_app/includes/success_enter_link_modal.html'), name='verify_email_success'),
        path('password-recovery/', TemplateAPIView.as_view(template_name=''),
             name='password_recovery'),
        path('password-sent/', TemplateAPIView.as_view(template_name='auth_app/reset_password_sent.html'),
             name='reset_email_sent'),

    ]

web/src/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from .yasg import urlpatterns as swagger_url
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

admin_url = settings.ADMIN_URL

urlpatterns = [
    path('actions/', include('actions.urls')),
    path('user-profile/', include('user_profile.urls')),
    path('', include('main.urls')),
    path('auth/', include('auth_app.urls')),
    path('', include('blog.urls')),
    path('', include('contact_us.urls')),
    path(f'{admin_url}/', admin.site.urls),
    path(f'{admin_url}/defender/', include('defender.urls')),
    path('api/', include('rest_framework.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('about/', include('about.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += swagger_url

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    if settings.ENABLE_SILK:
        urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]
    if settings.ENABLE_DEBUG_TOOLBAR:
        from debug_toolbar import urls

        urlpatterns += [path('__debug__/', include(urls))]

web/auth_app/models.py
from django.db import models

from . import managers

# Create your models here.

web/auth_app/forms.py
from allauth.account.models import EmailAddress
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from rest_framework.exceptions import ValidationError
from rest_framework.reverse import reverse_lazy
# from main.services import CeleryService, UserService
from main.services import UserService, CeleryService


User = get_user_model()


class PassResetForm(PasswordResetForm):

    def get_reset_url(self, uid, token):
        path = "auth_app:password_reset_confirm"
        url = reverse_lazy(path, kwargs={'uidb64': uid, 'token': token})
        return settings.FRONTEND_SITE + str(url)

    def save(self, domain_override=None,
             subject_template_name='account/email/password_reset_subject.txt',
             email_template_name='account/email/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None, html_email_template_name='account/email/password_reset_email.html',
             extra_email_context=None, **kwargs):
        """
        Generate a one-use only link for resetting password and send it to the user.
        """
        email = self.cleaned_data["email"]
        # email = EmailAddress.objects.get(user=User)
        user = UserService.get_user(email=email)
        if not user:
            raise ValidationError({'email': _('User does not exist with this email')})
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        token = token_generator.make_token(user)
        url = self.get_reset_url(uid=uid, token=token)

        data = {
            'to_email': email,
            'content': {
                'user': user.get_full_name(),
                'reset_url': url,
            }
        }
        CeleryService.send_password_reset(data=data)

web/auth_app/views.py
import logging

import django
from django.contrib.auth import logout as django_logout

from dj_rest_auth import views as auth_views
from dj_rest_auth.registration.views import (
    VerifyEmailView as _VerifyEmailView,
)
from django.views.generic.base import TemplateResponseMixin, TemplateView
from rest_framework.generics import CreateAPIView
from rest_framework.permissions import AllowAny

from . import serializers
from .services import full_logout

logger = logging.getLogger(__name__)


class LoginView(auth_views.LoginView):
    serializer_class = serializers.LoginSerializer


class SignUpView(CreateAPIView):
    permission_classes = (AllowAny,)
    serializer_class = serializers.UserSignUpSerializer


class PasswordResetView(auth_views.PasswordResetView):
    serializer_class = serializers.PasswordResetSerializer


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    serializer_class = serializers.PasswordResetConfirmSerializer


class VerifyEmailView(_VerifyEmailView):

    def get_serializer(self, *args, **kwargs):
        return serializers.VerifyEmailSerializer(*args, **kwargs)


class LogoutView(auth_views.LogoutView):
    allowed_methods = ('POST', 'OPTIONS')

    def session_logout(self):
        django_logout(self.request)

    def logout(self, request):
        self.session_logout()
        response = full_logout(request)
        return response

web/auth_app/templates/auth_app/includes/birthday.html
{% load i18n %}
<div id="birthdayGroup">
<label for="birthday">{% trans 'Enter your date of birth:'%}</label>
<input type="date" name="birthday" id="birthday" class="form-control input-lg" min="">
</div>

web/auth_app/templates/auth_app/includes/forgot_password_modal.html
<!--modal-->
<div id="pwdModal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h1 class="text-center">Reset Password?</h1>
      </div>
      <div class="modal-body">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="text-center">

                <p>If you have forgotten your password you can reset it here.</p>
                <div class="panel-body">
                  <fieldset>
                    <form id="forgotPasswordForm" role="form" action="{% url 'auth_app:api_forgot_password' %}" method="post">
                      {% csrf_token %}
                      <div id="emailForgotGroup" class="form-group">
                        <input class="form-control input-lg" placeholder="E-mail Address" name="email" type="email" required>
                      </div>
                      <input href="#" class="btn btn-lg btn-success btn-block" value="Reset password" type="submit">
                    </form>
                  </fieldset>
                  <div id="successPassReset" data-href="{% url 'auth_app:reset_email_sent' %}"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <div class="col-md-12">
          <button class="btn" data-dismiss="modal" aria-hidden="true">Cancel</button>
        </div>
      </div>
    </div>
  </div>
</div>
{% include 'auth_app/includes/forgot_password_modal_success.html' %}

web/auth_app/templates/auth_app/includes/forgot_password_modal_success.html
<!--modal-->
<div id="pwdModalSecond" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
      <div class="modal-body">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="text-center">
                <p>We have sent you a reset email</p>
                <div class="panel-body">
                  <fieldset>
                    <form id="forgotPasswordFormSuccess" role="form" action="{% url 'auth_app:login' %}">
                      <input class="btn btn-lg btn-success btn-block" value="Return to blog site" type="submit">
                    </form>
                  </fieldset>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

web/auth_app/templates/auth_app/includes/gender.html
<label>Gender : </label>
<div id="genderGroup">
<label class="radio-inline">
  <input type="radio" name="gender" value="0" id=male/> Male
</label>
<label class="radio-inline">
  <input type="radio" name="gender" value="1" id=female/> Female
</label>
</div>

web/auth_app/templates/auth_app/includes/password.html
<div id="password1Group">
<input type="password" name="password1" value="" class="form-control input-lg" placeholder="Password"/>
</div>
<div id="password2Group">
<input type="password" name="password2" value="" class="form-control input-lg" placeholder="Confirm Password"/>
</div>

web/auth_app/templates/auth_app/includes/prevent_access.html
{% if user.is_authenticated %}
<script>
  window.location.replace("{% url 'index' %}")
</script>
{% endif %}

web/auth_app/templates/auth_app/includes/reset_password_email_link.html
{% load static %}
{% load i18n main %}
{% microservice_title as site_name %}
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<script>
  $(document).ready(function(){
    $.getScript('{% static 'auth_app/js/password_confirmation.js' %}');
    {% block jquery %} {% endblock jquery %}
})
</script>
<div class="container">
<div class="row">
<div class="col-sm-12">
<h1>Change Password</h1>
</div>
</div>
<div class="row">
<div class="col-sm-6 col-sm-offset-3">
<p class="text-center">Use the form below to change your password. Your password cannot be the same as your username.</p>
<form method="post" id="passwordForm" action="{% url 'auth_app:password_reset_confirm_email' %}">
  {% csrf_token %}
<input type="password" class="input-lg form-control" name="password1" id="password1" placeholder="New Password" autocomplete="off">
<div class="row">
<div class="col-sm-6">
<span id="8char" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> 8 Characters Long<br>
<span id="ucase" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> One Uppercase Letter
</div>
<div class="col-sm-6">
<span id="lcase" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> One Lowercase Letter<br>
<span id="num" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> One Number
</div>
</div>
<input type="password" class="input-lg form-control" name="password2" id="password2" placeholder="Repeat Password" autocomplete="off">
<div class="row">
<div class="col-sm-12">
<span id="pwmatch" class="glyphicon glyphicon-remove" style="color:#FF0004;"></span> Passwords Match
</div>
</div>
<input type="submit" class="col-xs-12 btn btn-primary btn-load btn-lg" data-loading-text="Changing Password..." value="Change Password">
</form>
</div><!--/col-sm-6-->
</div><!--/row-->
</div>

web/auth_app/templates/auth_app/includes/sign_up_new_user_modal.html
<!--modal-->
<div id="pwdModalSignUp" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">

      <div class="modal-body">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-body">
              <div class="text-center">

                <p>Congratulation the registration was made without mistakes!</p>
                <div class="panel-body">
                  <form id="buttonForm" action="{% url 'auth_app:login' %}" class="form" role="form" >
                  <fieldset>
                      <button class="btn btn-lg btn-primary btn-block signup-btn" type="submit" id = "clickMe">
                          Click this button to finish your registration!
                      </button>
                  </fieldset>
                  </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>