web/auth_app/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.conf import settings
from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import TokenRefreshView, TokenVerifyView
from main.views import TemplateAPIView
from . import views

app_name = 'auth_app'

router = DefaultRouter()

urlpatterns = [
    path('token/refresh/', TokenRefreshView.as_view()),
    path('token/verify/', TokenVerifyView.as_view()),
]

urlpatterns += [
    path('sign-in/', views.LoginView.as_view(), name='api_login'),
    path('sign-up/', views.SignUpView.as_view(), name='api_sign_up'),
    path('sign-up/verify/', views.VerifyEmailView.as_view(), name='api_sign_up_verify'),
    path('password/reset/', views.PasswordResetView.as_view(), name='api_forgot_password'),
    path('password/reset/confirm/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm_email'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

urlpatterns += router.urls

urlpatterns += [
    path('password-reset/<uidb64>/<token>/', TemplateView.as_view(
        template_name='auth_app/includes/reset_password_email_link.html'), name='password_reset_confirm'),
    path('verify-email/<key>/', TemplateAPIView.as_view(template_name='auth_app/success_enter_link.html'),
         name='account_verification'),
]

if settings.ENABLE_RENDERING:
    urlpatterns += [
        path('login/', TemplateAPIView.as_view(template_name='auth_app/login.html'), name='login'),
        path('register/', TemplateAPIView.as_view(template_name='auth_app/sign_up.html'), name='sign_up'),
        path('verify-email/success', TemplateAPIView.as_view(
            template_name='auth_app/includes/success_enter_link_modal.html'), name='verify_email_success'),
        path('password-recovery/', TemplateAPIView.as_view(template_name=''),
             name='password_recovery'),
        path('password-sent/', TemplateAPIView.as_view(template_name='auth_app/reset_password_sent.html'),
             name='reset_email_sent'),

    ]

web/src/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from .yasg import urlpatterns as swagger_url
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

admin_url = settings.ADMIN_URL

urlpatterns = [
    path('actions/', include('actions.urls')),
    path('user-profile/', include('user_profile.urls')),
    path('', include('main.urls')),
    path('auth/', include('auth_app.urls')),
    path('', include('blog.urls')),
    path('', include('contact_us.urls')),
    path(f'{admin_url}/', admin.site.urls),
    path(f'{admin_url}/defender/', include('defender.urls')),
    path('api/', include('rest_framework.urls')),
    path('rosetta/', include('rosetta.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('about/', include('about.urls')),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
]

urlpatterns += swagger_url

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    if settings.ENABLE_SILK:
        urlpatterns += [path('silk/', include('silk.urls', namespace='silk'))]
    if settings.ENABLE_DEBUG_TOOLBAR:
        from debug_toolbar import urls

        urlpatterns += [path('__debug__/', include(urls))]

web/auth_app/models.py
from django.db import models

from . import managers

# Create your models here.

web/auth_app/forms.py
from allauth.account.models import EmailAddress
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from rest_framework.exceptions import ValidationError
from rest_framework.reverse import reverse_lazy
# from main.services import CeleryService, UserService
from main.services import UserService, CeleryService


User = get_user_model()


class PassResetForm(PasswordResetForm):

    def get_reset_url(self, uid, token):
        path = "auth_app:password_reset_confirm"
        url = reverse_lazy(path, kwargs={'uidb64': uid, 'token': token})
        return settings.FRONTEND_SITE + str(url)

    def save(self, domain_override=None,
             subject_template_name='account/email/password_reset_subject.txt',
             email_template_name='account/email/password_reset_email.html',
             use_https=False, token_generator=default_token_generator,
             from_email=None, request=None, html_email_template_name='account/email/password_reset_email.html',
             extra_email_context=None, **kwargs):
        """
        Generate a one-use only link for resetting password and send it to the user.
        """
        email = self.cleaned_data["email"]
        # email = EmailAddress.objects.get(user=User)
        user = UserService.get_user(email=email)
        if not user:
            raise ValidationError({'email': _('User does not exist with this email')})
        uid = urlsafe_base64_encode(force_bytes(user.pk))
        token = token_generator.make_token(user)
        url = self.get_reset_url(uid=uid, token=token)

        data = {
            'to_email': email,
            'content': {
                'user': user.get_full_name(),
                'reset_url': url,
            }
        }
        CeleryService.send_password_reset(data=data)

web/auth_app/views.py
import logging

import django
from django.contrib.auth import logout as django_logout

from dj_rest_auth import views as auth_views
from dj_rest_auth.registration.views import (
    VerifyEmailView as _VerifyEmailView,
)
from django.views.generic.base import TemplateResponseMixin, TemplateView
from rest_framework.generics import CreateAPIView
from rest_framework.permissions import AllowAny

from . import serializers
from .services import full_logout

logger = logging.getLogger(__name__)


class LoginView(auth_views.LoginView):
    serializer_class = serializers.LoginSerializer


class SignUpView(CreateAPIView):
    permission_classes = (AllowAny,)
    serializer_class = serializers.UserSignUpSerializer


class PasswordResetView(auth_views.PasswordResetView):
    serializer_class = serializers.PasswordResetSerializer


class PasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    serializer_class = serializers.PasswordResetConfirmSerializer


class VerifyEmailView(_VerifyEmailView):

    def get_serializer(self, *args, **kwargs):
        return serializers.VerifyEmailSerializer(*args, **kwargs)


class LogoutView(auth_views.LogoutView):
    allowed_methods = ('POST', 'OPTIONS')

    def session_logout(self):
        django_logout(self.request)

    def logout(self, request):
        self.session_logout()
        response = full_logout(request)
        return response

web/auth_app/templates/auth_app/base.html
{% extends 'base.html' %}

web/auth_app/templates/auth_app/login.html
{% extends 'auth_app/base.html'%}
{% load static %}

{% block head %}
<link href="{% static 'auth_app/css/login.css' %}" rel="stylesheet">
{% endblock head %}

{% block container %}
{% include 'auth_app/includes/prevent_access.html' %}

<div class="row" style="margin-top:20px">
  <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">
    <form id="loginForm" role="form" action="{% url 'auth_app:api_login' %}" method="post">
      {% csrf_token %}
      <fieldset>
        <h2>Please Sign In</h2>
        <hr class="colorgraph">
        <div id="emailGroup" class="form-group">
          <input type="email" name="email" id="email" class="form-control input-lg" placeholder="Email Address">
        </div>
        <div id="passwordGroup" class="form-group">
          <input type="password" name="password" id="password" class="form-control input-lg" placeholder="Password">
        </div>
        <span class="button-checkbox">
					<button type="button" class="btn" data-color="info">Remember Me</button>
                    <input type="checkbox" name="remember_me" id="remember_me" checked="checked" class="hidden">
					<a href="#" class="btn btn-link pull-right" data-toggle="modal" data-target="#pwdModal">Forgot Password?</a>
				</span>
        <hr class="colorgraph">
        <div class="row">
          <div class="col-xs-6 col-sm-6 col-md-6">
            <input type="submit" class="btn btn-lg btn-success btn-block" value="Sign In">
          </div>
          <div class="col-xs-6 col-sm-6 col-md-6">
            <a href="{% url 'auth_app:sign_up' %}" class="btn btn-lg btn-primary btn-block">Register</a>
          </div>
        </div>
      </fieldset>
    </form>
  </div>
</div>
{% include 'auth_app/includes/forgot_password_modal.html' %}
{% endblock container %}

{% block jquery %}
$.getScript('{% static 'auth_app/js/login.js' %}');
{% endblock %}

web/auth_app/templates/auth_app/sign_up.html
{% extends 'auth_app/base.html'%}
{% load static i18n %}

{% block head %}
<link href="{% static 'auth_app/css/sign_up.css' %}" rel="stylesheet">
{% endblock head %}

{% block container %}
{% include 'auth_app/includes/prevent_access.html' %}

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <form id="signUpForm" action="{% url 'auth_app:api_sign_up' %}" method="post" accept-charset="utf-8" class="form" role="form">
      <legend>Sign Up</legend>
      <h4>It's free and always will be.</h4>
      <div class="row">
        <div class="col-xs-6 col-md-6" id="firstNameGroup">
          <input type="text" name="first_name" value="" class="form-control input-lg" placeholder="First Name"/></div>
        <div class="col-xs-6 col-md-6" id="lastNameGroup">
          <input type="text" name="last_name" value="" class="form-control input-lg" placeholder="Last Name"/></div>
      </div>
        <div id="emailGroup">
        <input type="text" name="email" value="" class="form-control input-lg" placeholder="Your Email"/>
      </div>
      {% include 'auth_app/includes/password.html' %}
      {% include 'auth_app/includes/birthday.html' %}
      {% include 'auth_app/includes/gender.html' %}
      <br/>
      <span class="help-block">By clicking Create my account, you agree to our Terms and that you have read our Data Use Policy, including our Cookie Use.</span>
        <button href="#" data-toggle="modal" data-target="#pwdModalSignUp" class="btn btn-lg btn-primary btn-block signup-btn" type="submit">
              Create my account
        </button>
    </form>
  </div>
</div>
{% include 'auth_app/includes/sign_up_new_user_modal.html' %}
{% endblock container %}

{% block jquery %}
$.getScript('{% static 'auth_app/js/sign-up.js' %}');
{% endblock %}